---
title: "Centrality R Shiny"
author: "Mengyong Lee"
date: "4/22/2020"
output: html_document
---

```{r}
# busstop information
busstops <- read.csv("data/busstop_lonlat_subzone_District.csv")%>%
  dplyr::filter(planning_area != "Invalid")
busstops$BusStopCode <- as.integer(busstops$BusStopCode)
busstops$BusStopCode <- as.character(busstops$BusStopCode)
busstops$planning_area <- as.character(busstops$planning_area)
busstops$planning_area[busstops$planning_area %in% c('Central Water Catchment', 'Mandai', 'Marina South', 'Museum', 'Newton', 'Orchard', 'Outram', 
                                                                           'Seletar', 'Rochor', 'Singapore River', 'Tanglin', 'Southern Islands', 'River Valley', 'Paya Lebar', 
                                                                           'Straits View', 'Tengah')] <- "Others"

#bus route
busroute <- read_csv('data/bus_route_overall.csv')
busroute$BusStopCode <- as.integer(busroute$BusStopCode)
busroute$BusStopCode <- as.character(busroute$BusStopCode)
busroute <- busroute[c('BusStopCode', 'Direction', 'Distance', 'ServiceNo', 'StopSequence')]
busroute <- busroute[busroute$BusStopCode %in% as.list(unique(busstops['BusStopCode']))[['BusStopCode']], ] 

```

```{r}
busroute_2 <- busroute
busroute_2['StopSequence'] = busroute_2['StopSequence']-1
busroute_2['BusStopCode_dest'] = busroute_2['BusStopCode']
busroute_2 <- busroute_2[c('BusStopCode_dest', 'Direction', 'ServiceNo', 'StopSequence')]
busstops_from_to <- dplyr::inner_join(busroute, busroute_2, by =c('StopSequence', 'ServiceNo', 'Direction'))

#join the two tables together
busroute_busstop <- dplyr::inner_join(busstops_from_to, busstops, by ='BusStopCode')
keeps <- c('BusStopCode', 'BusStopCode_dest')
busroute_busstop <- busroute_busstop[, keeps, drop = FALSE] %>% 
  rename(from = BusStopCode) %>%
  rename(to = BusStopCode_dest)

busroute_busstop
```

```{r}
#groupby
busroute_busstop_aggregated <- busroute_busstop %>%
  #group_by(from, to, planning_area) %>%
  group_by(from, to) %>%
  summarise(Weight = n()) %>%
  dplyr::filter(from!=to) %>%
  dplyr::filter(Weight > 0) %>%
  ungroup()
busroute_busstop_aggregated$from <- as.character(busroute_busstop_aggregated$from)
busroute_busstop_aggregated$to <- as.character(busroute_busstop_aggregated$to)

busroute_busstop_aggregated
```

```{r}

#nodes
nodes_my <- busstops %>%
  rename(id = BusStopCode)
nodes_my$id <- as.character(nodes_my$id)

#create graph structure
bus_graph <- tbl_graph(nodes = nodes_my, edges = busroute_busstop_aggregated, directed = TRUE)
```

```{r}


#extract centrality
bus_graph_2=bus_graph%>%mutate(betweenness_centrality = centrality_betweenness(normalized = TRUE)) %>%mutate(closeness_centrality = centrality_closeness(normalized = TRUE)) %>%
  mutate(degree_centrality=centrality_degree(mode='out',normalized = TRUE))
bus_graph_2 = bus_graph_2 %>% mutate(eigen_centrality=centrality_eigen(weight = bus_graph$betweenness_centrality, directed = TRUE, scale = FALSE))

plot_vector2<- as.data.frame(cbind(V(bus_graph)$Longitude,V(bus_graph)$Latitude,V(bus_graph)$betweenness_centrality,V(bus_graph)$closeness_centrality,
                                   V(bus_graph)$eigen_centrality,V(bus_graph)$degree_centrality))


map_table <- plot_vector2 %>%
  rename(c(long.f = V1, lat.f = V2, between.f = V3, closeness.f = V4, eigen.f = V5, degree.f = V6))%>%
  dplyr::left_join(busstops, by =c("long.f"= "Longitude", "lat.f" = "Latitude")) 

range01 <- function(x){(x-min(x))/(max(x)-min(x))}

map_table$between.f <-round(range01(map_table$between.f),3)
map_table$closeness.f <-round(range01(map_table$closeness.f),3)

map_table$eigen.f <-round(range01(log(map_table$eigen.f+1)**0.15),3)


map_table$degree.f <-round(range01(map_table$degree.f),3)

write.csv(map_table ,"map_table.csv", row.names = FALSE)

map_table

```


```{r}

#get edge table
plot_vector2<- as.data.frame(cbind(V(bus_graph)$Longitude,V(bus_graph)$Latitude,V(bus_graph)$betweenness_centrality,V(bus_graph)$closeness_centrality,
                                   V(bus_graph)$eigen_centrality,V(bus_graph)$degree_centrality))

edgelist <- get.edgelist(bus_graph)
edgelist[,1]<-as.numeric(match(edgelist[,1],V(bus_graph)))
edgelist[,2]<-as.numeric(match(edgelist[,2],V(bus_graph)))

node1=data.frame(plot_vector2[edgelist[,1],])
node2=data.frame(plot_vector2[edgelist[,2],])
node3=data.frame(cbind(node1,node2))

edge_table <- node3 %>%
  rename(c(long.f = V1, lat.f = V2, long.t = V1.1, lat.t = V2.1, between.f = V3, closeness.f = V4, eigen.f = V5, degree.f = V6))%>%
  dplyr::left_join(busstops, by =c("long.f"= "Longitude", "lat.f" = "Latitude")) 

keeps <- c("long.f","lat.f","long.t","lat.t", "planning_area", 'subzone_name', "between.f", "closeness.f", "eigen.f","degree.f" )
edge_table <- edge_table[ , (names(edge_table) %in% keeps)]

range01 <- function(x){(x-min(x))/(max(x)-min(x))}

edge_table$between.f <-range01(edge_table$between.f)
edge_table$closeness.f <-range01(edge_table$closeness.f)
edge_table$eigen.f <-range01(edge_table$eigen.f)
edge_table$degree.f <-range01(edge_table$degree.f)

# get node table
map_table <- plot_vector2 %>%
  rename(c(long.f = V1, lat.f = V2, between.f = V3, closeness.f = V4, eigen.f = V5, degree.f = V6))%>%
  dplyr::left_join(busstops, by =c("long.f"= "Longitude", "lat.f" = "Latitude")) 

map_table$between.f <-round(range01(map_table$between.f),3)
map_table$closeness.f <-round(range01(map_table$closeness.f),3)
map_table$eigen.f <-round(range01(map_table$eigen.f),3)
map_table$degree.f <-round(range01(map_table$degree.f),3)

#get the radius of the bubbles
map_table$combined.f = (map_table$between.f*3+1)**(3/4) + (map_table$closeness.f*3+1)**(3/4) + (map_table$eigen.f*3+1)**(3/4) + (map_table$degree.f*3+1)**(3/4)

```

```{r}
map_nodes <- map_table
map_edges <- edge_table

map3 <- map_nodes %>% leaflet()%>%
  addProviderTiles("CartoDB") %>% 
  setMaxBounds(lng1 = 103.801959 + .25, 
               lat1 = 1.32270 + .25, 
               lng2 = 103.801959 - .25, 
               lat2 = 1.32270 - .25)

for(i in 1:nrow(map_edges)){
map3 <- addPolylines(map3, lat = as.numeric(map_edges[i, c('lat.f', 'lat.t')]), 
                     lng = as.numeric(map_edges[i, c('long.f', 'long.t')]),
                     weight = 0.75,
                     color = 'red'
)
}

for(i in 1:nrow(map_nodes)){
map3<-addCircleMarkers(map3, lat = as.numeric(map_nodes[i, 'lat.f']), 
                       lng = as.numeric(map_nodes[i,'long.f']),
                       radius =(as.numeric(map_nodes[i, 'combined.f'])*0.7*40),
                       color='blue',
                       fillOpacity = 0.75,
                       label = map_nodes[i,'id.Description'],
                       popup = ~paste0("<b>", map_nodes[i,'Description'], "</b>", "<br/>", 'Betweenness Centrality: ', round(map_nodes[i,'between.f'],3), "<br/>", 
                                       'Closeness Centrality: ', round(map_nodes[i,'closeness.f'],3), "<br/>", 'Eigenvalue Centrality: ', round(map_nodes[i,'eigen.f'],3), 
                                       "<br/>", 'Degree Centrality: ', round(map_nodes[i,'degree.f'],3))
)}
map3

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

