---
title: "Centrality R Shiny"
author: "Mengyong Lee"
date: "4/22/2020"
output: html_document
---

```{r}
# busstop volume

library(shiny)
library(tidyverse)
library(shinydashboard)
library(flows)
library(sp)
library(maptools)
library(st)
library(sf)
library(leaflet)
library(reshape2)
library(igraph)
library(ggraph)
library(tidygraph)
library(tmap)
library(flows)
library(sp)
library(RColorBrewer)

busstop_volume <- read.csv("data/passenger volume by busstop.csv")
colnames(busstop_volume)[5] = "BusStopCode"
busstop_volume$BusStopCode <- as.character(busstop_volume$BusStopCode)


# busstop information
busstops <- read.csv("data/busstop_lonlat_subzone_District.csv")%>%
  dplyr::filter(planning_area != "Invalid")
busstops$BusStopCode <- as.integer(busstops$BusStopCode)
busstops$BusStopCode <- as.character(busstops$BusStopCode)
busstops$planning_area <- as.character(busstops$planning_area)
busstops$planning_area[busstops$planning_area %in% c('Central Water Catchment', 'Mandai', 'Marina South', 'Museum', 'Newton', 'Orchard', 'Outram', 
                                                                           'Seletar', 'Rochor', 'Singapore River', 'Tanglin', 'Southern Islands', 'River Valley', 'Paya Lebar', 
                                                                           'Straits View', 'Tengah')] <- "Others"

#bus route
busroute <- read_csv('data/bus_route_overall.csv')
busroute$BusStopCode <- as.integer(busroute$BusStopCode)
busroute$BusStopCode <- as.character(busroute$BusStopCode)
busroute <- busroute[c('BusStopCode', 'Direction', 'Distance', 'ServiceNo', 'StopSequence')]
busroute <- busroute[busroute$BusStopCode %in% as.list(unique(busstops['BusStopCode']))[['BusStopCode']], ] 

```

```{r}
library(plyr)
busstop_volume_lat_long_my <- dplyr::inner_join(busstop_volume, busstops, by ='BusStopCode')
location_my <- busstop_volume_lat_long_my %>%
  dplyr::group_by(BusStopCode)%>%
  dplyr::arrange(desc(BusStopCode))%>%
  dplyr::rename(c(lat = Latitude, lon = Longitude))

location_my$tap_in_out_radius <- (location_my$TOTAL_TAP_IN_VOLUME + location_my$TOTAL_TAP_OUT_VOLUME)**(1/2)/6
location_my <- location_my[c('planning_area', 'subzone_name', 'DAY_TYPE', 'TIME_PER_HOUR', 'BusStopCode', 'Description', 'RoadName', 'TOTAL_TAP_IN_VOLUME', 'TOTAL_TAP_OUT_VOLUME', 'lon', 'lat', 'tap_in_out_radius')]%>%
  dplyr::rename(c(Day = DAY_TYPE, TapIns = TOTAL_TAP_IN_VOLUME, TapOuts = TOTAL_TAP_OUT_VOLUME, Time = TIME_PER_HOUR, PlanningArea = planning_area)) %>%
  dplyr::filter(Time >=6 & Time <= 23)
  
#location_my$Time <- mapvalues(location_my$Time, from=c(6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23), 
#          to=c("06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00"))

planning_area_list_my <-sort(unique(location_my$PlanningArea))

                                            # choices = c('06:00' = 6,'07:00' = 7,'08:00' = 8,'09:00' = 9,'10:00' = 10,'11:00' = 11,'12:00' = 12,'13:00' = 13,
                                            #             '14:00' = 14,'15:00' = 15,'16:00' = 16,'17:00' = 17,'18:00' = 18,'19:00' = 19,'20:00' = 20, '21:00' = 21,
                                            #             '22:00' = 22,'23:00' = 23),

pal <- colorNumeric(palette = "RdPu", domain = location_my$tap_in_out_radius)

```

```{r}
#location_my$Time = as.character(location_my$Time)
head(location_my)

```
```{r}
location_subzone = location_my %>% 
  dplyr::filter(PlanningArea == 'Ang Mo Kio') %>% 
  dplyr::group_by(Time)%>%
  dplyr::summarise(TapIns = sum(TapIns)/1000, TapOuts = sum(TapOuts)/1000)%>%
  dplyr::ungroup()
  #tidyr::pivot_longer(-Time, names_to  = "Taps", values_to = "Count")
  
head(location_subzone)

#busroute_busstop_aggregated <- busroute_busstop %>%
#  #group_by(from, to, planning_area) %>%
#  group_by(from, to) %>%
#  summarise(Weight = n()) %>%
#  dplyr::filter(from!=to) %>%
#  dplyr::filter(Weight > 0) %>%
#  ungroup()

```

```{r}
location_subzone %>%
  plot_ly(x = ~Time, y = ~TapIns, type = "scatter", mode = "lines", color = I('dark green'), name = "Tap Ins") %>%
  add_trace(x = ~Time, y = ~TapOuts, type = "scatter", mode = "lines", color = I('red'), name = "Tap Outs") %>%
  layout(title = "Passenger Volume",
         xaxis = list(title = "Time"),
         yaxis = list(title = "Number of Tap Ins / Tap Outs"))

```
```{r}
library (ggthemes)
library (plotly)

ggideal_point <- ggplot(location_subzone) +
  geom_line(aes(x=Time, y=Count, by=Taps, color=Taps)) +
  labs(x = "Year") +
  labs(y = "Ideology") +
  labs(title = "Ideal Points for Countries") +
  scale_colour_hue("clarity",l=70, c=150) +
  theme_few()

# Year range
min_Year <- min(location_subzone$Time)
max_Year <- max(location_subzone$Time)

ggideal_point
```

```{r}
gg <- gg2list(ggideal_point)

return(list(
    list(
        id="trendPlot",
        task="newPlot",
        data=gg$data,
        layout=gg$layout
    )
))

```

```{r, fig.height=5, fig.width=10}
library(CGPfunctions)
library(ggplot2)
library(gridExtra)

adr<- newggslopegraph(location_subzone, Time, Count, Taps,
                 XTextSize = 8, YTextSize = 8, WiderLabels=FALSE) +
  labs(title="Number of Tap Ins/Tapouts",
       subtitle= NULL)

adr
#ydr <- newggslopegraph(location_subzone, Time, TapOuts, subzone_name,
#                 XTextSize = 10, YTextSize = 3, WiderLabels=TRUE) +
#  labs(title="Number of Tap Outs by Subzone",
#        subtitle= NULL)+
#  theme(plot.caption = element_text(hjust = 0.5,size = 10))

#grid.arrange(adr, ydr, ncol = 2)


```

```{r}

ggplot(location_subzone) +
  geom_line(aes(x = Time, y = Count, colour = Taps))

```


```{r}
#map_data <- location_my
#map_data %>% leaflet()%>%
#  addProviderTiles("CartoDB") %>% 
#  addCircleMarkers(lng = ~lon, 
#                   lat = ~lat,
#                   radius = ~tap_in_out_radius/1.5,
#                   fillOpacity = 0.5,
#                   label = ~Description, 
#                   popup = ~paste0("<b>", Description, "</b>", "<br/>", 'Tap in Volume: ', TapIns, "<br/>", 'Tap out volume: ', TapOuts),
#                   color = 'black',
#                   weight = 0.5,
#                   fillColor = ~pal(tap_in_out_radius)
#  ) %>%
#  setMaxBounds(lng1 = 103.801959 + .25, 
#               lat1 = 1.32270 + .25, 
#               lng2 = 103.801959 - .25, 
#               lat2 = 1.32270 - .25)
  
```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

