---
title: "Mapping of Bus Route"
author: "Mengyong Lee"
date: "4/7/2020"
output: html_document
---

```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
packages = c('igraph', 'tidygraph', 'ggraph', 'visNetwork', 'lubridate', 'tidyverse', 'ggplot2', 'ggmap', 'leaflet', 'ggiraph', 'sf', 'tmap')

for(p in packages){library
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}

#top_bus <- c('51','61','961','66','67','14','30','143','10','147','178','197','154','167','166','174','196','171','2','12','21','170','970','13')

proper= function(s) sub("(.)", ("\\U\\1"), tolower(s), pe=TRUE)

busstops <- read_csv('data/busstops_with_planning_area_XY.csv')
busstops$BusStopCode <- as.character(busstops$BusStopCode)
busstops <- busstops[c('BusStopCode', 'Description', 'RoadName', 'planning_area', 'Latitude', 'Longitude')]

busstops
```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
busroute <- read_csv('data/bus_route_overall.csv')
busroute$BusStopCode <- as.character(busroute$BusStopCode)
busroute <- busroute[c('BusStopCode', 'Direction', 'Distance', 'ServiceNo', 'StopSequence')]
 #       %>% dplyr::filter(ServiceNo %in% top_bus)

busroute <- busroute[busroute$BusStopCode %in% as.list(unique(busstops['BusStopCode']))[['BusStopCode']], ] 

busroute
```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
busroute_2 <- busroute

busroute_2['StopSequence'] = busroute_2['StopSequence']-1
busroute_2['BusStopCode_dest'] = busroute_2['BusStopCode']
busroute_2 <- busroute_2[c('BusStopCode_dest', 'Direction', 'ServiceNo', 'StopSequence')]

busstops_from_to <- dplyr::inner_join(busroute, busroute_2, by =c('StopSequence', 'ServiceNo', 'Direction'))
busstops_from_to

```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
#join the two tables together

busroute_busstop <- dplyr::inner_join(busstops_from_to, busstops, by ='BusStopCode')
keeps <- c('BusStopCode', 'BusStopCode_dest', 'Direction', 'Distance', 'ServiceNo', 'Latitude', 'Longitude', 'planning_area', 'Description')
busroute_busstop <- busroute_busstop[, keeps, drop = FALSE] %>% 
                rename(to_bus = BusStopCode_dest) %>%
                rename(from = planning_area)

busroute_busstop <- dplyr::inner_join(busroute_busstop, busstops[c('BusStopCode', 'planning_area')]%>%rename(to_bus = BusStopCode), by ='to_bus')%>%
              rename(to = planning_area)

head(busroute_busstop)
```

```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
busroute_busstop_aggregated <- busroute_busstop %>%
  group_by(from, to) %>%
    summarise(Weight = n()) %>%
  filter(from!=to) %>%
  filter(Weight > 1) %>%
  filter(from!='Invalid') %>%
  filter(to!='Invalid') %>%
  ungroup()

busroute_busstop_aggregated$from <- as.character(busroute_busstop_aggregated$from)
busroute_busstop_aggregated$to <- as.character(busroute_busstop_aggregated$to)

busroute_busstop_aggregated
```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
center_of_gravity <- busstops %>%
  rename(id = planning_area)%>%
  group_by(id) %>%
  summarise(Latitude =mean(Latitude), Longitude = mean(Longitude))

center_of_gravity

```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
bus_graph <- tbl_graph(nodes = center_of_gravity, edges = busroute_busstop_aggregated, directed = TRUE)

#          activate(edges) %>%
#          arrange(desc(Weight))
#%>%
 #         filter(id %in% union(.E()$to, .E()$from))
bus_graph
```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
bus_graph=bus_graph%>%mutate(betweenness_centrality = centrality_betweenness(normalized = T)) %>%mutate(closeness_centrality = centrality_closeness(normalized = T))%>%mutate(centrality_degree=centrality_degree(mode='out',normalized = T))%>%mutate(centrality_eigen=centrality_eigen(weights=bus_graph$Weight,directed=T))

bus_graph
```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
G=bus_graph

#Normally we need to create two vectors in order to plot both the network data and the coordinates on a map
#plot_vector takes the longitude and latitude to be plotted on a map.
#plot_vector1 takes the lon, lat and the network centrality values.
plot_vector<- as.data.frame(cbind(V(G)$Longitude,V(G)$Latitude))
plot_vector1<- as.data.frame(cbind(V(G)$Longitude,V(G)$Latitude,V(G)$betweenness_centrality,V(G)$closeness_centrality))
#plot_vector1<- as.data.frame(cbind(V(G)$Longitude,V(G)$Latitude,V(G)$betweenness_centrality,V(G)$closeness_centrality,V(G)$centrality_eigen,V(G)$centrality_degree, V(G)$id))


#we are taking the edgelist which is being used to get the origin and destination of the airport data.
#edgelist[,1]- takes the origin values and the edgelist[,2] takes the destination values.
edgelist <- get.edgelist(G)
edgelist[,1]<-as.numeric(match(edgelist[,1],V(G)))
edgelist[,2]<-as.numeric(match(edgelist[,2],V(G)))

#the edges now consists of the edge between the origin and the destination values
edges <- data.frame(plot_vector[edgelist[,1],], plot_vector[edgelist[,2],])

#naming the coloumns obtained to plot
colnames(edges) <- c("X1","Y1","X2","Y2")

#Here we are taking ggmap as our base layer. on top of ggmap we are plotting the origin and destination coordinates using the plot_vector as our 2nd layer, then we are plotting the coordinates of all the centrality from the plot_vector1 as our 3rd layer and then we are ploting the geom_segment i.e. the edges as our 4th layer.
```

```{r, echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE}
register_google(key = "AIzaSyAVz4L7AGlC88pfMCHpxgKNH9hle3gxW9o")
```


``` {r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, fig.height=4, fig.width=6}

#Singapore
map <- get_map(location = c(lon = 103.8279248, lat = 1.3438295), zoom=11, source = "google", maptype = 'roadmap')
#Queenstown
#map <- get_map(location = c(lon = 103.7662684, lat = 1.2869421), zoom=14, source = "google", maptype = 'toner')

p <- ggmap(map) 

z=p + 
  geom_segment(aes(x=X1, y=Y1, xend = X2, yend = Y2), color='black',data=edges,arrow = arrow(length = unit(0.2,"cm")))+ 
  #geom_point(aes(V1, V2), data=plot_vector1)+
  geom_point(aes(x=V1,y=V2,
                 size=plot_vector1$V3,
                 colour=plot_vector1$V4),
                  plot_vector1[,0:4])+
  scale_colour_gradientn(colours=rainbow(5))+scale_size_continuous(range = c(1, 10))
z

```

```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, fig.height=20, fig.width=20}

#we use the node3 to get our origin and destination airport for plotting it on our map

#plot_vector2<- as.data.frame(cbind(V(G)$Longitude,V(G)$Latitude,V(G)$betweenness_centrality,V(G)$closeness_centrality))
plot_vector2<- as.data.frame(cbind(V(G)$Longitude,V(G)$Latitude,V(G)$betweenness_centrality,V(G)$closeness_centrality,V(G)$centrality_eigen,V(G)$centrality_degree))

node1=data.frame(plot_vector2[edgelist[,1],])
node2=data.frame(plot_vector2[edgelist[,2],])
node3=data.frame(cbind(node1,node2))



map_table <- node3 %>%
  rename(c(long.f = V1, lat.f = V2, between.f = V3, closeness.f = V4, eigen.f = V5, degree.f = V6,
           long.t = V1.1, lat.t = V2.1, between.t = V3.1, closeness.t = V4.1, eigen.t = V5.1, degree.t = V6.1))%>%
  dplyr::left_join(center_of_gravity[c('id', 'Longitude')] %>% rename(id.f = id), by =c("long.f" = "Longitude")) %>%
  dplyr::left_join(center_of_gravity[c('id', 'Longitude')] %>% rename(id.t = id), by =c("long.t" = "Longitude"))

map_table

```


```{r}
#Then we use a for loop in order to put the destination and origin airport on to the leaflet

map3 = leaflet(map_table) %>%
  addProviderTiles("CartoDB", group = "CartoDB") %>% 
  addTiles() %>%
    setMaxBounds(lng1 = 103.801959 + .25, 
               lat1 = 1.32270 + .25, 
               lng2 = 103.801959 - .25, 
               lat2 = 1.32270 - .25)

for(i in 1:nrow(node3)){
    map3 <- addPolylines(map3, lat = as.numeric(map_table[i, c('lat.f', 'lat.t')]), 
                               lng = as.numeric(map_table[i, c('long.f', 'long.t')]),
                                weight = 0.5,
                                color = 'black')
    
    #origin
    map3<-addCircleMarkers(map3, lat = as.numeric(map_table[i, 'lat.f']), 
                               lng = as.numeric(map_table[i,'long.f']),radius =(as.numeric(map_table[i, 'between.f'])*50),color='darkred',
                               label = map_table[i,'id.f'],
                             popup = ~paste0("<b>", map_table[i,'id.f'], "</b>", "<br/>", 'Betweenness: ', round(map_table[i,'between.f'],2), "<br/>", 'Closeness: ', ... = round(map_table[i,'closeness.f'],2), "<br/>", 'Eigenvalue: ', round(map_table[i,'eigen.f'],2), "<br/>", 'Degree: ', round(map_table[i,'degree.f'],2))
                           )
    #destination
  #  map3<-addCircleMarkers(map3, lat = as.numeric(map_table[i, 'lat.t']), 
  #                             lng = as.numeric(map_table[i, 'long.t']),radius =(as.numeric(map_table[i, 'between.t'])),color='red' )
    
}
map3

```


```{r}
plot_vector2<- as.data.frame(cbind(V(G)$Longitude,V(G)$Latitude,V(G)$betweenness_centrality,V(G)$closeness_centrality,V(G)$centrality_eigen,V(G)$centrality_degree, V(G)$id))

node1=data.frame(plot_vector1[edgelist[,1],])
node2=data.frame(plot_vector1[edgelist[,2],])
node4=data.frame(cbind(node1,node2))

```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, fig.height=15, fig.width=15}
map_2 <- get_map(location = c(lon = 103.7662684, lat = 1.2869421), zoom=14, source = "google", maptype = 'roadmap')

```


```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, fig.height=15, fig.width=15}

bus_graph$layout=cbind(V(bus_graph)$Longitude,V(bus_graph)$Latitude)

#arrow formating
a <- arrow(type = "closed", length = unit(.09, "inches"))

#from the below code we are telling ggmap to take ggraph as your base layer with layout as the cordinates. 
#Here we get the curvature using geom_edge_arc.

g<-ggmap(map_2, fullpage = TRUE, base_layer = ggraph(bus_graph)) + 
  geom_edge_arc(aes(edge_size=E(bus_graph)$centrality_degree),edge_colour = 'red', edge_alpha = 0.5,curvature = 0.2, arrow=a, end_cap = circle(.008, 'inches')) 
 # geom_node_point(aes(colour = closeness_centrality,size=betweenness_centrality))+ scale_colour_gradientn(colours=rainbow(3))+scale_size_continuous(range = c(1, 10))

plot(g)


```
```{r}

#$centrality_degree

E(bus_graph)

```